name: helloGithubAction

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # run 두 실제 작동하는 코드를 넣어야 합니다.
    - name: hello word 출력!!
      run: echo hello, world!
    - name: 디렉토리 출력!!
      run: ls -al
    - name: 파이썬 버전 출력!!
      run: python -V
